### ISSUE TITLE
Missing USB protection diode on PCB

### ISSUE THREAD

**Issue by arekm** [dvjcodec/Due3dom-Mini#1]
Current PCB is missing a diode that is supposed to prevent 5V from inverter to go back to USB.

Fix is to cut the trace and solder 12V/1A schottky diode.

![fix2](https://cloud.githubusercontent.com/assets/50869/22383217/20c763e6-e4c9-11e6-80ee-4608c96e15bf.jpg)

Fix from http://www.fabrykator.pl/board/viewtopic.php?p=12128#p12128

**Comment by dvjcodec** [comment]
Fixed in rev.2
